<#
.SYNOPSIS
loginScript.ps1 - Script to create an vbs file to run each powershell file in a custom script location

.DESCRIPTION 
This script will only create the scheduled task for the vbscript, eventually the VBScript will take over the login part.

.OUTPUTS
vbs file in customscripts
schedule task created

.NOTES
Author: Ian Weedlun
Version   : 1.1 @ March 9th, 2022
Original Author    : Rutger Hermarij from https://scatty.nl/blog
#>

$content = @"
' ******************************************************************************
' loginScript.vbs
' Author    : Rutger Hermarij
' from      : https://scatty.nl/blog
' Date      : 12-02-2020
' Version:  1.0
' This script is generated by the login.ps1 file (from Azure) 
' and just runs all the scripts that are located on the CustomScriptLocation
' ******************************************************************************

Set objShell    = CreateObject("WScript.Shell")                              ' possiblility to Shell  files from the OS
Set objFSO      = CreateObject("Scripting.FileSystemObject")			     ' possiblility to access the file system from the OS
oProgramData    = objShell.ExpandEnvironmentStrings("%ALLUSERSPROFILE%")     ' need to know the PorgramData location from the OS
CustomScriptLoc = oProgramData & "\CustomScripts\"                           ' and the location of the custom scripts             


' now lets create a for loop for all the files that are in this folder
For Each oFile in objFSO.GetFolder(CustomScriptLoc).Files
  ' lets first put the hit counter 1 
  ' Filter out only the ps1 extension
  If LCase(objFSO.GetExtensionName(oFile.Name)) = "ps1" Then
    ' wscript.echo oFile.Name ' debug
	' run the script
	RunScript(oFile.Name)
   End If
Next

' Sub function for running the actual file.
Sub RunScript(file) 
  ' First Check if the file exists
  If objFSO.FileExists(CustomScriptLoc & file) Then
    objShell.LogEvent 4,"running script: "&CustomScriptLoc & file
    objExec  =  objShell.Run ("powershell.exe -ex bypass -file "&CustomScriptLoc & file,0,1)
  End If
End Sub

"@

# create custom folder and write PS script
$path = $(Join-Path $env:ProgramData CustomScripts)
if (!(Test-Path $path)) {
  New-Item -Path $path -ItemType Directory -Force -Confirm:$false
  }
Out-File -FilePath $(Join-Path $env:ProgramData CustomScripts\loginScript.vbs) -Encoding unicode -Force -InputObject $content -Confirm:$false

# register script as scheduled task
$Time = New-ScheduledTaskTrigger -AtLogon
$action = New-ScheduledTaskAction -Execute "wscript.exe" -Argument "`"$env:ProgramData\CustomScripts\loginScript.vbs`""
$principal = New-ScheduledTaskPrincipal -UserID "NT AUTHORITY\SYSTEM" -LogonType ServiceAccount -RunLevel Highest
$settings = New-ScheduledTaskSettingsSet -MultipleInstances Parallel
Register-ScheduledTask -Description "Login script for Azure joined machines, this script will execute powershell scripts." -TaskName "loginScript" -Trigger $Time -Action $action -Settings $settings -Principal $principal -Force 
#EOF